### PR TITLE
New Ginger sample

### PR DESCRIPTION
**Pull request by aolney**
This PR ports the [Stickman Ventures Ginger Demo](https://github.com/StickmanVentures/ginger) , viewable [here](https://sv-ginger.appspot.com/) to Electron via fable.

A few things from Ginger were left out (google analytics/bower related) and a few fixes made (some modal windows weren't closing).

The license is Apache 2 b/c that's what Ginger is. Also note they have a CC Noncommercial on the 3D assets. I left that license right where they did in the source tree.

PS Please let me know if I can do something better with these PRs. I found that if I merged with upstream GitHub can automatically merge, but there seems to be a lot of old commit history below.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Fantastic, thank you! I need to give this a try, looks super cool :clap: The PR looks fine to me, there're some merge commits but I think the only way to avoid this is by rebasing which can be a bit confusing sometimes. In any case, I usually use the `Squash and merge` Github feature to merge the PRs so it will appear as a single commit in `master` history.

If you're interested in collaborating more with Fable, I've sent you an invitation to join the team! 👍 If you accept it you'll have write access to this repo. It's probably better if we keep using PRs to update `master` but you can work on custom branches directly in the repo if you want :)

**Comment by aolney** [comment]
Awesome, thanks!

**Comment by aolney** [comment]
Just to clarify, do you want to review pull requests to master, or can I merge them?

**Comment by alfonsogarciacaro** [comment]
If I'm available, let me have a look just in case. If I don't reply for several days call the police and merge the PR 😄

**Comment by aolney** [comment]
Sounds good

**Pull request merged**
